// Code generated by MockGen. DO NOT EDIT.
// Source: app.go
//
// Generated by this command:
//
//	mockgen -source=app.go -destination=./mock/app.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "bkauth/pkg/service/types"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAppService is a mock of AppService interface.
type MockAppService struct {
	ctrl     *gomock.Controller
	recorder *MockAppServiceMockRecorder
	isgomock struct{}
}

// MockAppServiceMockRecorder is the mock recorder for MockAppService.
type MockAppServiceMockRecorder struct {
	mock *MockAppService
}

// NewMockAppService creates a new mock instance.
func NewMockAppService(ctrl *gomock.Controller) *MockAppService {
	mock := &MockAppService{ctrl: ctrl}
	mock.recorder = &MockAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppService) EXPECT() *MockAppServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppService) Create(ctx context.Context, app types.App, createdSource string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app, createdSource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAppServiceMockRecorder) Create(ctx, app, createdSource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppService)(nil).Create), ctx, app, createdSource)
}

// CreateWithSecret mocks base method.
func (m *MockAppService) CreateWithSecret(ctx context.Context, app types.App, appSecret, createdSource string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithSecret", ctx, app, appSecret, createdSource)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithSecret indicates an expected call of CreateWithSecret.
func (mr *MockAppServiceMockRecorder) CreateWithSecret(ctx, app, appSecret, createdSource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithSecret", reflect.TypeOf((*MockAppService)(nil).CreateWithSecret), ctx, app, appSecret, createdSource)
}

// Delete mocks base method.
func (m *MockAppService) Delete(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAppServiceMockRecorder) Delete(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAppService)(nil).Delete), ctx, code)
}

// Exists mocks base method.
func (m *MockAppService) Exists(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockAppServiceMockRecorder) Exists(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockAppService)(nil).Exists), ctx, code)
}

// Get mocks base method.
func (m *MockAppService) Get(ctx context.Context, code string) (types.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, code)
	ret0, _ := ret[0].(types.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAppServiceMockRecorder) Get(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppService)(nil).Get), ctx, code)
}

// List mocks base method.
func (m *MockAppService) List(ctx context.Context, tenantMode, tenantID string, page, pageSize int, orderBy, orderByDirection string) (int, []types.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantMode, tenantID, page, pageSize, orderBy, orderByDirection)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]types.App)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAppServiceMockRecorder) List(ctx, tenantMode, tenantID, page, pageSize, orderBy, orderByDirection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAppService)(nil).List), ctx, tenantMode, tenantID, page, pageSize, orderBy, orderByDirection)
}

// NameExists mocks base method.
func (m *MockAppService) NameExists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NameExists indicates an expected call of NameExists.
func (mr *MockAppServiceMockRecorder) NameExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameExists", reflect.TypeOf((*MockAppService)(nil).NameExists), ctx, name)
}
