// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_token.go
//
// Generated by this command:
//
//	mockgen -source=oauth_token.go -destination=./mock/oauth_token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "bkauth/pkg/service/types"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthTokenService is a mock of OAuthTokenService interface.
type MockOAuthTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthTokenServiceMockRecorder
	isgomock struct{}
}

// MockOAuthTokenServiceMockRecorder is the mock recorder for MockOAuthTokenService.
type MockOAuthTokenServiceMockRecorder struct {
	mock *MockOAuthTokenService
}

// NewMockOAuthTokenService creates a new mock instance.
func NewMockOAuthTokenService(ctrl *gomock.Controller) *MockOAuthTokenService {
	mock := &MockOAuthTokenService{ctrl: ctrl}
	mock.recorder = &MockOAuthTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthTokenService) EXPECT() *MockOAuthTokenServiceMockRecorder {
	return m.recorder
}

// GetAccessTokenByTokenHash mocks base method.
func (m *MockOAuthTokenService) GetAccessTokenByTokenHash(ctx context.Context, tokenHash string) (types.ResolvedAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(types.ResolvedAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenByTokenHash indicates an expected call of GetAccessTokenByTokenHash.
func (mr *MockOAuthTokenServiceMockRecorder) GetAccessTokenByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenByTokenHash", reflect.TypeOf((*MockOAuthTokenService)(nil).GetAccessTokenByTokenHash), ctx, tokenHash)
}

// IssueTokensForAuthorizationCode mocks base method.
func (m *MockOAuthTokenService) IssueTokensForAuthorizationCode(ctx context.Context, realmName, clientID, tenantID, sub, username string, audience []string, policy types.TokenIssuancePolicy) (types.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokensForAuthorizationCode", ctx, realmName, clientID, tenantID, sub, username, audience, policy)
	ret0, _ := ret[0].(types.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokensForAuthorizationCode indicates an expected call of IssueTokensForAuthorizationCode.
func (mr *MockOAuthTokenServiceMockRecorder) IssueTokensForAuthorizationCode(ctx, realmName, clientID, tenantID, sub, username, audience, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokensForAuthorizationCode", reflect.TypeOf((*MockOAuthTokenService)(nil).IssueTokensForAuthorizationCode), ctx, realmName, clientID, tenantID, sub, username, audience, policy)
}

// IssueTokensForDeviceCode mocks base method.
func (m *MockOAuthTokenService) IssueTokensForDeviceCode(ctx context.Context, realmName, clientID, tenantID, sub, username string, audience []string, policy types.TokenIssuancePolicy) (types.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokensForDeviceCode", ctx, realmName, clientID, tenantID, sub, username, audience, policy)
	ret0, _ := ret[0].(types.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokensForDeviceCode indicates an expected call of IssueTokensForDeviceCode.
func (mr *MockOAuthTokenServiceMockRecorder) IssueTokensForDeviceCode(ctx, realmName, clientID, tenantID, sub, username, audience, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokensForDeviceCode", reflect.TypeOf((*MockOAuthTokenService)(nil).IssueTokensForDeviceCode), ctx, realmName, clientID, tenantID, sub, username, audience, policy)
}

// RefreshAccessToken mocks base method.
func (m *MockOAuthTokenService) RefreshAccessToken(ctx context.Context, realmName, refreshToken, clientID string, policy types.TokenIssuancePolicy) (types.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessToken", ctx, realmName, refreshToken, clientID, policy)
	ret0, _ := ret[0].(types.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshAccessToken indicates an expected call of RefreshAccessToken.
func (mr *MockOAuthTokenServiceMockRecorder) RefreshAccessToken(ctx, realmName, refreshToken, clientID, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessToken", reflect.TypeOf((*MockOAuthTokenService)(nil).RefreshAccessToken), ctx, realmName, refreshToken, clientID, policy)
}

// RevokeByGrantID mocks base method.
func (m *MockOAuthTokenService) RevokeByGrantID(ctx context.Context, grantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByGrantID", ctx, grantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByGrantID indicates an expected call of RevokeByGrantID.
func (mr *MockOAuthTokenServiceMockRecorder) RevokeByGrantID(ctx, grantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByGrantID", reflect.TypeOf((*MockOAuthTokenService)(nil).RevokeByGrantID), ctx, grantID)
}

// RevokeToken mocks base method.
func (m *MockOAuthTokenService) RevokeToken(ctx context.Context, tokenHash, clientID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, tokenHash, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockOAuthTokenServiceMockRecorder) RevokeToken(ctx, tokenHash, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockOAuthTokenService)(nil).RevokeToken), ctx, tokenHash, clientID)
}
