// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_device_code.go
//
// Generated by this command:
//
//	mockgen -source=oauth_device_code.go -destination=./mock/oauth_device_code.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "bkauth/pkg/service/types"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthDeviceCodeService is a mock of OAuthDeviceCodeService interface.
type MockOAuthDeviceCodeService struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthDeviceCodeServiceMockRecorder
	isgomock struct{}
}

// MockOAuthDeviceCodeServiceMockRecorder is the mock recorder for MockOAuthDeviceCodeService.
type MockOAuthDeviceCodeServiceMockRecorder struct {
	mock *MockOAuthDeviceCodeService
}

// NewMockOAuthDeviceCodeService creates a new mock instance.
func NewMockOAuthDeviceCodeService(ctrl *gomock.Controller) *MockOAuthDeviceCodeService {
	mock := &MockOAuthDeviceCodeService{ctrl: ctrl}
	mock.recorder = &MockOAuthDeviceCodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthDeviceCodeService) EXPECT() *MockOAuthDeviceCodeServiceMockRecorder {
	return m.recorder
}

// ApproveByUserCode mocks base method.
func (m *MockOAuthDeviceCodeService) ApproveByUserCode(ctx context.Context, userCode, sub, username string, audience []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveByUserCode", ctx, userCode, sub, username, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveByUserCode indicates an expected call of ApproveByUserCode.
func (mr *MockOAuthDeviceCodeServiceMockRecorder) ApproveByUserCode(ctx, userCode, sub, username, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveByUserCode", reflect.TypeOf((*MockOAuthDeviceCodeService)(nil).ApproveByUserCode), ctx, userCode, sub, username, audience)
}

// CreateDeviceCode mocks base method.
func (m *MockOAuthDeviceCodeService) CreateDeviceCode(ctx context.Context, realmName, clientID, resource string) (types.CreatedDeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceCode", ctx, realmName, clientID, resource)
	ret0, _ := ret[0].(types.CreatedDeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeviceCode indicates an expected call of CreateDeviceCode.
func (mr *MockOAuthDeviceCodeServiceMockRecorder) CreateDeviceCode(ctx, realmName, clientID, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceCode", reflect.TypeOf((*MockOAuthDeviceCodeService)(nil).CreateDeviceCode), ctx, realmName, clientID, resource)
}

// DenyByUserCode mocks base method.
func (m *MockOAuthDeviceCodeService) DenyByUserCode(ctx context.Context, userCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DenyByUserCode", ctx, userCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// DenyByUserCode indicates an expected call of DenyByUserCode.
func (mr *MockOAuthDeviceCodeServiceMockRecorder) DenyByUserCode(ctx, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DenyByUserCode", reflect.TypeOf((*MockOAuthDeviceCodeService)(nil).DenyByUserCode), ctx, userCode)
}

// GetByUserCode mocks base method.
func (m *MockOAuthDeviceCodeService) GetByUserCode(ctx context.Context, userCode string) (types.PendingDeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserCode", ctx, userCode)
	ret0, _ := ret[0].(types.PendingDeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserCode indicates an expected call of GetByUserCode.
func (mr *MockOAuthDeviceCodeServiceMockRecorder) GetByUserCode(ctx, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserCode", reflect.TypeOf((*MockOAuthDeviceCodeService)(nil).GetByUserCode), ctx, userCode)
}

// PollAndConsumeDeviceCode mocks base method.
func (m *MockOAuthDeviceCodeService) PollAndConsumeDeviceCode(ctx context.Context, realmName, deviceCode, clientID string) (types.ApprovedDeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollAndConsumeDeviceCode", ctx, realmName, deviceCode, clientID)
	ret0, _ := ret[0].(types.ApprovedDeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollAndConsumeDeviceCode indicates an expected call of PollAndConsumeDeviceCode.
func (mr *MockOAuthDeviceCodeServiceMockRecorder) PollAndConsumeDeviceCode(ctx, realmName, deviceCode, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollAndConsumeDeviceCode", reflect.TypeOf((*MockOAuthDeviceCodeService)(nil).PollAndConsumeDeviceCode), ctx, realmName, deviceCode, clientID)
}
