// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_authorization_code.go
//
// Generated by this command:
//
//	mockgen -source=oauth_authorization_code.go -destination=./mock/oauth_authorization_code.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "bkauth/pkg/service/types"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthAuthorizationCodeService is a mock of OAuthAuthorizationCodeService interface.
type MockOAuthAuthorizationCodeService struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthAuthorizationCodeServiceMockRecorder
	isgomock struct{}
}

// MockOAuthAuthorizationCodeServiceMockRecorder is the mock recorder for MockOAuthAuthorizationCodeService.
type MockOAuthAuthorizationCodeServiceMockRecorder struct {
	mock *MockOAuthAuthorizationCodeService
}

// NewMockOAuthAuthorizationCodeService creates a new mock instance.
func NewMockOAuthAuthorizationCodeService(ctrl *gomock.Controller) *MockOAuthAuthorizationCodeService {
	mock := &MockOAuthAuthorizationCodeService{ctrl: ctrl}
	mock.recorder = &MockOAuthAuthorizationCodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthAuthorizationCodeService) EXPECT() *MockOAuthAuthorizationCodeServiceMockRecorder {
	return m.recorder
}

// CreateAuthorizationCode mocks base method.
func (m *MockOAuthAuthorizationCodeService) CreateAuthorizationCode(ctx context.Context, input types.CreateAuthorizationCodeInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthorizationCode", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuthorizationCode indicates an expected call of CreateAuthorizationCode.
func (mr *MockOAuthAuthorizationCodeServiceMockRecorder) CreateAuthorizationCode(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthorizationCode", reflect.TypeOf((*MockOAuthAuthorizationCodeService)(nil).CreateAuthorizationCode), ctx, input)
}

// ValidateAndConsume mocks base method.
func (m *MockOAuthAuthorizationCodeService) ValidateAndConsume(ctx context.Context, realmName, code, clientID, redirectURI, codeVerifier string) (types.ConsumedAuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndConsume", ctx, realmName, code, clientID, redirectURI, codeVerifier)
	ret0, _ := ret[0].(types.ConsumedAuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndConsume indicates an expected call of ValidateAndConsume.
func (mr *MockOAuthAuthorizationCodeServiceMockRecorder) ValidateAndConsume(ctx, realmName, code, clientID, redirectURI, codeVerifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndConsume", reflect.TypeOf((*MockOAuthAuthorizationCodeService)(nil).ValidateAndConsume), ctx, realmName, code, clientID, redirectURI, codeVerifier)
}
