// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_client.go
//
// Generated by this command:
//
//	mockgen -source=oauth_client.go -destination=./mock/oauth_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "bkauth/pkg/service/types"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthClientService is a mock of OAuthClientService interface.
type MockOAuthClientService struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthClientServiceMockRecorder
	isgomock struct{}
}

// MockOAuthClientServiceMockRecorder is the mock recorder for MockOAuthClientService.
type MockOAuthClientServiceMockRecorder struct {
	mock *MockOAuthClientService
}

// NewMockOAuthClientService creates a new mock instance.
func NewMockOAuthClientService(ctrl *gomock.Controller) *MockOAuthClientService {
	mock := &MockOAuthClientService{ctrl: ctrl}
	mock.recorder = &MockOAuthClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthClientService) EXPECT() *MockOAuthClientServiceMockRecorder {
	return m.recorder
}

// DynamicRegister mocks base method.
func (m *MockOAuthClientService) DynamicRegister(ctx context.Context, input types.OAuthClientDynamicRegistrationInput) (types.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DynamicRegister", ctx, input)
	ret0, _ := ret[0].(types.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DynamicRegister indicates an expected call of DynamicRegister.
func (mr *MockOAuthClientServiceMockRecorder) DynamicRegister(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DynamicRegister", reflect.TypeOf((*MockOAuthClientService)(nil).DynamicRegister), ctx, input)
}

// Exists mocks base method.
func (m *MockOAuthClientService) Exists(ctx context.Context, clientID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockOAuthClientServiceMockRecorder) Exists(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockOAuthClientService)(nil).Exists), ctx, clientID)
}

// Get mocks base method.
func (m *MockOAuthClientService) Get(ctx context.Context, clientID string) (types.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, clientID)
	ret0, _ := ret[0].(types.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOAuthClientServiceMockRecorder) Get(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOAuthClientService)(nil).Get), ctx, clientID)
}

// GetFlowSpec mocks base method.
func (m *MockOAuthClientService) GetFlowSpec(ctx context.Context, clientID string) (types.OAuthClientFlowSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowSpec", ctx, clientID)
	ret0, _ := ret[0].(types.OAuthClientFlowSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowSpec indicates an expected call of GetFlowSpec.
func (mr *MockOAuthClientServiceMockRecorder) GetFlowSpec(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowSpec", reflect.TypeOf((*MockOAuthClientService)(nil).GetFlowSpec), ctx, clientID)
}

// GetProfile mocks base method.
func (m *MockOAuthClientService) GetProfile(ctx context.Context, clientID string) (types.OAuthClientProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, clientID)
	ret0, _ := ret[0].(types.OAuthClientProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockOAuthClientServiceMockRecorder) GetProfile(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockOAuthClientService)(nil).GetProfile), ctx, clientID)
}
