// Code generated by MockGen. DO NOT EDIT.
// Source: personal_access_token.go
//
// Generated by this command:
//
//	mockgen -source=personal_access_token.go -destination=./mock/personal_access_token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "bkauth/pkg/service/types"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPersonalAccessTokenService is a mock of PersonalAccessTokenService interface.
type MockPersonalAccessTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalAccessTokenServiceMockRecorder
	isgomock struct{}
}

// MockPersonalAccessTokenServiceMockRecorder is the mock recorder for MockPersonalAccessTokenService.
type MockPersonalAccessTokenServiceMockRecorder struct {
	mock *MockPersonalAccessTokenService
}

// NewMockPersonalAccessTokenService creates a new mock instance.
func NewMockPersonalAccessTokenService(ctrl *gomock.Controller) *MockPersonalAccessTokenService {
	mock := &MockPersonalAccessTokenService{ctrl: ctrl}
	mock.recorder = &MockPersonalAccessTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalAccessTokenService) EXPECT() *MockPersonalAccessTokenServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPersonalAccessTokenService) Create(ctx context.Context, input types.CreatePersonalAccessTokenInput, policy types.PersonalTokenPolicy) (types.CreatedPersonalAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input, policy)
	ret0, _ := ret[0].(types.CreatedPersonalAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPersonalAccessTokenServiceMockRecorder) Create(ctx, input, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPersonalAccessTokenService)(nil).Create), ctx, input, policy)
}

// GetByIDAndSub mocks base method.
func (m *MockPersonalAccessTokenService) GetByIDAndSub(ctx context.Context, realmName string, id int64, sub string) (types.PersonalAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndSub", ctx, realmName, id, sub)
	ret0, _ := ret[0].(types.PersonalAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndSub indicates an expected call of GetByIDAndSub.
func (mr *MockPersonalAccessTokenServiceMockRecorder) GetByIDAndSub(ctx, realmName, id, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndSub", reflect.TypeOf((*MockPersonalAccessTokenService)(nil).GetByIDAndSub), ctx, realmName, id, sub)
}

// GetByTokenHash mocks base method.
func (m *MockPersonalAccessTokenService) GetByTokenHash(ctx context.Context, tokenHash string) (types.ResolvedAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(types.ResolvedAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockPersonalAccessTokenServiceMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockPersonalAccessTokenService)(nil).GetByTokenHash), ctx, tokenHash)
}

// ListByOwner mocks base method.
func (m *MockPersonalAccessTokenService) ListByOwner(ctx context.Context, realmName, sub, state string) ([]types.PersonalAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOwner", ctx, realmName, sub, state)
	ret0, _ := ret[0].([]types.PersonalAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOwner indicates an expected call of ListByOwner.
func (mr *MockPersonalAccessTokenServiceMockRecorder) ListByOwner(ctx, realmName, sub, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOwner", reflect.TypeOf((*MockPersonalAccessTokenService)(nil).ListByOwner), ctx, realmName, sub, state)
}

// Renew mocks base method.
func (m *MockPersonalAccessTokenService) Renew(ctx context.Context, realmName string, id int64, sub string, expiresIn int64, policy types.PersonalTokenPolicy) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx, realmName, id, sub, expiresIn, policy)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Renew indicates an expected call of Renew.
func (mr *MockPersonalAccessTokenServiceMockRecorder) Renew(ctx, realmName, id, sub, expiresIn, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockPersonalAccessTokenService)(nil).Renew), ctx, realmName, id, sub, expiresIn, policy)
}

// Revoke mocks base method.
func (m *MockPersonalAccessTokenService) Revoke(ctx context.Context, realmName string, id int64, sub string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, realmName, id, sub)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockPersonalAccessTokenServiceMockRecorder) Revoke(ctx, realmName, id, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockPersonalAccessTokenService)(nil).Revoke), ctx, realmName, id, sub)
}

// Update mocks base method.
func (m *MockPersonalAccessTokenService) Update(ctx context.Context, input types.UpdatePersonalAccessTokenInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPersonalAccessTokenServiceMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPersonalAccessTokenService)(nil).Update), ctx, input)
}
