// Code generated by MockGen. DO NOT EDIT.
// Source: target.go
//
// Generated by this command:
//
//	mockgen -source=target.go -destination=./mock/target.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "bkauth/pkg/service/types"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTargetService is a mock of TargetService interface.
type MockTargetService struct {
	ctrl     *gomock.Controller
	recorder *MockTargetServiceMockRecorder
	isgomock struct{}
}

// MockTargetServiceMockRecorder is the mock recorder for MockTargetService.
type MockTargetServiceMockRecorder struct {
	mock *MockTargetService
}

// NewMockTargetService creates a new mock instance.
func NewMockTargetService(ctrl *gomock.Controller) *MockTargetService {
	mock := &MockTargetService{ctrl: ctrl}
	mock.recorder = &MockTargetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetService) EXPECT() *MockTargetServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTargetService) Create(target types.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTargetServiceMockRecorder) Create(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTargetService)(nil).Create), target)
}

// Exists mocks base method.
func (m *MockTargetService) Exists(id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockTargetServiceMockRecorder) Exists(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockTargetService)(nil).Exists), id)
}

// Get mocks base method.
func (m *MockTargetService) Get(id string) (types.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(types.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTargetServiceMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTargetService)(nil).Get), id)
}

// Update mocks base method.
func (m *MockTargetService) Update(target types.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTargetServiceMockRecorder) Update(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTargetService)(nil).Update), target)
}
