// Code generated by MockGen. DO NOT EDIT.
// Source: app.go

// Package mock is a generated GoMock package.
package mock

import (
	dao "bkauth/pkg/database/dao"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
)

// MockAppManager is a mock of AppManager interface.
type MockAppManager struct {
	ctrl     *gomock.Controller
	recorder *MockAppManagerMockRecorder
}

// MockAppManagerMockRecorder is the mock recorder for MockAppManager.
type MockAppManagerMockRecorder struct {
	mock *MockAppManager
}

// NewMockAppManager creates a new mock instance.
func NewMockAppManager(ctrl *gomock.Controller) *MockAppManager {
	mock := &MockAppManager{ctrl: ctrl}
	mock.recorder = &MockAppManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppManager) EXPECT() *MockAppManagerMockRecorder {
	return m.recorder
}

// CreateWithTx mocks base method.
func (m *MockAppManager) CreateWithTx(tx *sqlx.Tx, app dao.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", tx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockAppManagerMockRecorder) CreateWithTx(tx, app interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockAppManager)(nil).CreateWithTx), tx, app)
}

// Exists mocks base method.
func (m *MockAppManager) Exists(code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockAppManagerMockRecorder) Exists(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockAppManager)(nil).Exists), code)
}

// List mocks base method.
func (m *MockAppManager) List() ([]dao.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]dao.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAppManagerMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAppManager)(nil).List))
}

// NameExists mocks base method.
func (m *MockAppManager) NameExists(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameExists", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NameExists indicates an expected call of NameExists.
func (mr *MockAppManagerMockRecorder) NameExists(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameExists", reflect.TypeOf((*MockAppManager)(nil).NameExists), name)
}
