// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_refresh_token.go
//
// Generated by this command:
//
//	mockgen -source=oauth_refresh_token.go -destination=./mock/oauth_refresh_token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dao "bkauth/pkg/database/dao"
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthRefreshTokenManager is a mock of OAuthRefreshTokenManager interface.
type MockOAuthRefreshTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthRefreshTokenManagerMockRecorder
	isgomock struct{}
}

// MockOAuthRefreshTokenManagerMockRecorder is the mock recorder for MockOAuthRefreshTokenManager.
type MockOAuthRefreshTokenManagerMockRecorder struct {
	mock *MockOAuthRefreshTokenManager
}

// NewMockOAuthRefreshTokenManager creates a new mock instance.
func NewMockOAuthRefreshTokenManager(ctrl *gomock.Controller) *MockOAuthRefreshTokenManager {
	mock := &MockOAuthRefreshTokenManager{ctrl: ctrl}
	mock.recorder = &MockOAuthRefreshTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthRefreshTokenManager) EXPECT() *MockOAuthRefreshTokenManagerMockRecorder {
	return m.recorder
}

// CreateWithTx mocks base method.
func (m *MockOAuthRefreshTokenManager) CreateWithTx(ctx context.Context, tx *sqlx.Tx, token dao.OAuthRefreshToken) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, token)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockOAuthRefreshTokenManagerMockRecorder) CreateWithTx(ctx, tx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockOAuthRefreshTokenManager)(nil).CreateWithTx), ctx, tx, token)
}

// GetByTokenHash mocks base method.
func (m *MockOAuthRefreshTokenManager) GetByTokenHash(ctx context.Context, tokenHash string) (dao.OAuthRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(dao.OAuthRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockOAuthRefreshTokenManagerMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockOAuthRefreshTokenManager)(nil).GetByTokenHash), ctx, tokenHash)
}

// RevokeByGrantIDWithTx mocks base method.
func (m *MockOAuthRefreshTokenManager) RevokeByGrantIDWithTx(ctx context.Context, tx *sqlx.Tx, grantID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByGrantIDWithTx", ctx, tx, grantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeByGrantIDWithTx indicates an expected call of RevokeByGrantIDWithTx.
func (mr *MockOAuthRefreshTokenManagerMockRecorder) RevokeByGrantIDWithTx(ctx, tx, grantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByGrantIDWithTx", reflect.TypeOf((*MockOAuthRefreshTokenManager)(nil).RevokeByGrantIDWithTx), ctx, tx, grantID)
}

// RevokeIfNotRevokedWithTx mocks base method.
func (m *MockOAuthRefreshTokenManager) RevokeIfNotRevokedWithTx(ctx context.Context, tx *sqlx.Tx, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeIfNotRevokedWithTx", ctx, tx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeIfNotRevokedWithTx indicates an expected call of RevokeIfNotRevokedWithTx.
func (mr *MockOAuthRefreshTokenManagerMockRecorder) RevokeIfNotRevokedWithTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeIfNotRevokedWithTx", reflect.TypeOf((*MockOAuthRefreshTokenManager)(nil).RevokeIfNotRevokedWithTx), ctx, tx, id)
}

// RevokeWithTx mocks base method.
func (m *MockOAuthRefreshTokenManager) RevokeWithTx(ctx context.Context, tx *sqlx.Tx, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeWithTx", ctx, tx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeWithTx indicates an expected call of RevokeWithTx.
func (mr *MockOAuthRefreshTokenManagerMockRecorder) RevokeWithTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeWithTx", reflect.TypeOf((*MockOAuthRefreshTokenManager)(nil).RevokeWithTx), ctx, tx, id)
}
