// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_access_token.go
//
// Generated by this command:
//
//	mockgen -source=oauth_access_token.go -destination=./mock/oauth_access_token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dao "bkauth/pkg/database/dao"
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthAccessTokenManager is a mock of OAuthAccessTokenManager interface.
type MockOAuthAccessTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthAccessTokenManagerMockRecorder
	isgomock struct{}
}

// MockOAuthAccessTokenManagerMockRecorder is the mock recorder for MockOAuthAccessTokenManager.
type MockOAuthAccessTokenManagerMockRecorder struct {
	mock *MockOAuthAccessTokenManager
}

// NewMockOAuthAccessTokenManager creates a new mock instance.
func NewMockOAuthAccessTokenManager(ctrl *gomock.Controller) *MockOAuthAccessTokenManager {
	mock := &MockOAuthAccessTokenManager{ctrl: ctrl}
	mock.recorder = &MockOAuthAccessTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthAccessTokenManager) EXPECT() *MockOAuthAccessTokenManagerMockRecorder {
	return m.recorder
}

// CreateWithTx mocks base method.
func (m *MockOAuthAccessTokenManager) CreateWithTx(ctx context.Context, tx *sqlx.Tx, token dao.OAuthAccessToken) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, token)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockOAuthAccessTokenManagerMockRecorder) CreateWithTx(ctx, tx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockOAuthAccessTokenManager)(nil).CreateWithTx), ctx, tx, token)
}

// GetByTokenHash mocks base method.
func (m *MockOAuthAccessTokenManager) GetByTokenHash(ctx context.Context, tokenHash string) (dao.OAuthAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(dao.OAuthAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockOAuthAccessTokenManagerMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockOAuthAccessTokenManager)(nil).GetByTokenHash), ctx, tokenHash)
}

// Revoke mocks base method.
func (m *MockOAuthAccessTokenManager) Revoke(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockOAuthAccessTokenManagerMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockOAuthAccessTokenManager)(nil).Revoke), ctx, id)
}

// RevokeByGrantIDWithTx mocks base method.
func (m *MockOAuthAccessTokenManager) RevokeByGrantIDWithTx(ctx context.Context, tx *sqlx.Tx, grantID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByGrantIDWithTx", ctx, tx, grantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeByGrantIDWithTx indicates an expected call of RevokeByGrantIDWithTx.
func (mr *MockOAuthAccessTokenManagerMockRecorder) RevokeByGrantIDWithTx(ctx, tx, grantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByGrantIDWithTx", reflect.TypeOf((*MockOAuthAccessTokenManager)(nil).RevokeByGrantIDWithTx), ctx, tx, grantID)
}

// RevokeWithTx mocks base method.
func (m *MockOAuthAccessTokenManager) RevokeWithTx(ctx context.Context, tx *sqlx.Tx, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeWithTx", ctx, tx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeWithTx indicates an expected call of RevokeWithTx.
func (mr *MockOAuthAccessTokenManagerMockRecorder) RevokeWithTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeWithTx", reflect.TypeOf((*MockOAuthAccessTokenManager)(nil).RevokeWithTx), ctx, tx, id)
}
