// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_authorization_code.go
//
// Generated by this command:
//
//	mockgen -source=oauth_authorization_code.go -destination=./mock/oauth_authorization_code.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dao "bkauth/pkg/database/dao"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthAuthorizationCodeManager is a mock of OAuthAuthorizationCodeManager interface.
type MockOAuthAuthorizationCodeManager struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthAuthorizationCodeManagerMockRecorder
	isgomock struct{}
}

// MockOAuthAuthorizationCodeManagerMockRecorder is the mock recorder for MockOAuthAuthorizationCodeManager.
type MockOAuthAuthorizationCodeManagerMockRecorder struct {
	mock *MockOAuthAuthorizationCodeManager
}

// NewMockOAuthAuthorizationCodeManager creates a new mock instance.
func NewMockOAuthAuthorizationCodeManager(ctrl *gomock.Controller) *MockOAuthAuthorizationCodeManager {
	mock := &MockOAuthAuthorizationCodeManager{ctrl: ctrl}
	mock.recorder = &MockOAuthAuthorizationCodeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthAuthorizationCodeManager) EXPECT() *MockOAuthAuthorizationCodeManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOAuthAuthorizationCodeManager) Create(ctx context.Context, code dao.OAuthAuthorizationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOAuthAuthorizationCodeManagerMockRecorder) Create(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthAuthorizationCodeManager)(nil).Create), ctx, code)
}

// Get mocks base method.
func (m *MockOAuthAuthorizationCodeManager) Get(ctx context.Context, code string) (dao.OAuthAuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, code)
	ret0, _ := ret[0].(dao.OAuthAuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOAuthAuthorizationCodeManagerMockRecorder) Get(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOAuthAuthorizationCodeManager)(nil).Get), ctx, code)
}

// MarkAsUsed mocks base method.
func (m *MockOAuthAuthorizationCodeManager) MarkAsUsed(ctx context.Context, code string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, code)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockOAuthAuthorizationCodeManagerMockRecorder) MarkAsUsed(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockOAuthAuthorizationCodeManager)(nil).MarkAsUsed), ctx, code)
}
