// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_client.go
//
// Generated by this command:
//
//	mockgen -source=oauth_client.go -destination=./mock/oauth_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dao "bkauth/pkg/database/dao"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthClientManager is a mock of OAuthClientManager interface.
type MockOAuthClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthClientManagerMockRecorder
	isgomock struct{}
}

// MockOAuthClientManagerMockRecorder is the mock recorder for MockOAuthClientManager.
type MockOAuthClientManagerMockRecorder struct {
	mock *MockOAuthClientManager
}

// NewMockOAuthClientManager creates a new mock instance.
func NewMockOAuthClientManager(ctrl *gomock.Controller) *MockOAuthClientManager {
	mock := &MockOAuthClientManager{ctrl: ctrl}
	mock.recorder = &MockOAuthClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthClientManager) EXPECT() *MockOAuthClientManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOAuthClientManager) Create(ctx context.Context, client dao.OAuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOAuthClientManagerMockRecorder) Create(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthClientManager)(nil).Create), ctx, client)
}

// Exists mocks base method.
func (m *MockOAuthClientManager) Exists(ctx context.Context, clientID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockOAuthClientManagerMockRecorder) Exists(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockOAuthClientManager)(nil).Exists), ctx, clientID)
}

// Get mocks base method.
func (m *MockOAuthClientManager) Get(ctx context.Context, clientID string) (dao.OAuthClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, clientID)
	ret0, _ := ret[0].(dao.OAuthClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOAuthClientManagerMockRecorder) Get(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOAuthClientManager)(nil).Get), ctx, clientID)
}

// GetDisplay mocks base method.
func (m *MockOAuthClientManager) GetDisplay(ctx context.Context, clientID string) (dao.OAuthClientDisplay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDisplay", ctx, clientID)
	ret0, _ := ret[0].(dao.OAuthClientDisplay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDisplay indicates an expected call of GetDisplay.
func (mr *MockOAuthClientManagerMockRecorder) GetDisplay(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDisplay", reflect.TypeOf((*MockOAuthClientManager)(nil).GetDisplay), ctx, clientID)
}

// GetGrants mocks base method.
func (m *MockOAuthClientManager) GetGrants(ctx context.Context, clientID string) (dao.OAuthClientGrants, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrants", ctx, clientID)
	ret0, _ := ret[0].(dao.OAuthClientGrants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrants indicates an expected call of GetGrants.
func (mr *MockOAuthClientManagerMockRecorder) GetGrants(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrants", reflect.TypeOf((*MockOAuthClientManager)(nil).GetGrants), ctx, clientID)
}
