// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_device_code.go
//
// Generated by this command:
//
//	mockgen -source=oauth_device_code.go -destination=./mock/oauth_device_code.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dao "bkauth/pkg/database/dao"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthDeviceCodeManager is a mock of OAuthDeviceCodeManager interface.
type MockOAuthDeviceCodeManager struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthDeviceCodeManagerMockRecorder
	isgomock struct{}
}

// MockOAuthDeviceCodeManagerMockRecorder is the mock recorder for MockOAuthDeviceCodeManager.
type MockOAuthDeviceCodeManagerMockRecorder struct {
	mock *MockOAuthDeviceCodeManager
}

// NewMockOAuthDeviceCodeManager creates a new mock instance.
func NewMockOAuthDeviceCodeManager(ctrl *gomock.Controller) *MockOAuthDeviceCodeManager {
	mock := &MockOAuthDeviceCodeManager{ctrl: ctrl}
	mock.recorder = &MockOAuthDeviceCodeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthDeviceCodeManager) EXPECT() *MockOAuthDeviceCodeManagerMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockOAuthDeviceCodeManager) Approve(ctx context.Context, id int64, tenantID, sub, username, audience string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, id, tenantID, sub, username, audience)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Approve indicates an expected call of Approve.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) Approve(ctx, id, tenantID, sub, username, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).Approve), ctx, id, tenantID, sub, username, audience)
}

// ConsumeApproved mocks base method.
func (m *MockOAuthDeviceCodeManager) ConsumeApproved(ctx context.Context, deviceCode, clientID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeApproved", ctx, deviceCode, clientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeApproved indicates an expected call of ConsumeApproved.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) ConsumeApproved(ctx, deviceCode, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeApproved", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).ConsumeApproved), ctx, deviceCode, clientID)
}

// Create mocks base method.
func (m *MockOAuthDeviceCodeManager) Create(ctx context.Context, dc dao.OAuthDeviceCode) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) Create(ctx, dc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).Create), ctx, dc)
}

// GetByDeviceCode mocks base method.
func (m *MockOAuthDeviceCodeManager) GetByDeviceCode(ctx context.Context, deviceCode string) (dao.OAuthDeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDeviceCode", ctx, deviceCode)
	ret0, _ := ret[0].(dao.OAuthDeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDeviceCode indicates an expected call of GetByDeviceCode.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) GetByDeviceCode(ctx, deviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDeviceCode", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).GetByDeviceCode), ctx, deviceCode)
}

// GetByUserCode mocks base method.
func (m *MockOAuthDeviceCodeManager) GetByUserCode(ctx context.Context, userCode string) (dao.OAuthDeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserCode", ctx, userCode)
	ret0, _ := ret[0].(dao.OAuthDeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserCode indicates an expected call of GetByUserCode.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) GetByUserCode(ctx, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserCode", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).GetByUserCode), ctx, userCode)
}

// SlowDown mocks base method.
func (m *MockOAuthDeviceCodeManager) SlowDown(ctx context.Context, id, increment int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlowDown", ctx, id, increment)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SlowDown indicates an expected call of SlowDown.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) SlowDown(ctx, id, increment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlowDown", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).SlowDown), ctx, id, increment)
}

// UpdateLastPolledAt mocks base method.
func (m *MockOAuthDeviceCodeManager) UpdateLastPolledAt(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastPolledAt", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLastPolledAt indicates an expected call of UpdateLastPolledAt.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) UpdateLastPolledAt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastPolledAt", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).UpdateLastPolledAt), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockOAuthDeviceCodeManager) UpdateStatus(ctx context.Context, id int64, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOAuthDeviceCodeManagerMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOAuthDeviceCodeManager)(nil).UpdateStatus), ctx, id, status)
}
