// Code generated by MockGen. DO NOT EDIT.
// Source: personal_access_token.go
//
// Generated by this command:
//
//	mockgen -source=personal_access_token.go -destination=./mock/personal_access_token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dao "bkauth/pkg/database/dao"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPersonalAccessTokenManager is a mock of PersonalAccessTokenManager interface.
type MockPersonalAccessTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalAccessTokenManagerMockRecorder
	isgomock struct{}
}

// MockPersonalAccessTokenManagerMockRecorder is the mock recorder for MockPersonalAccessTokenManager.
type MockPersonalAccessTokenManagerMockRecorder struct {
	mock *MockPersonalAccessTokenManager
}

// NewMockPersonalAccessTokenManager creates a new mock instance.
func NewMockPersonalAccessTokenManager(ctrl *gomock.Controller) *MockPersonalAccessTokenManager {
	mock := &MockPersonalAccessTokenManager{ctrl: ctrl}
	mock.recorder = &MockPersonalAccessTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalAccessTokenManager) EXPECT() *MockPersonalAccessTokenManagerMockRecorder {
	return m.recorder
}

// CountActiveByOwner mocks base method.
func (m *MockPersonalAccessTokenManager) CountActiveByOwner(ctx context.Context, realmName, sub string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByOwner", ctx, realmName, sub)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByOwner indicates an expected call of CountActiveByOwner.
func (mr *MockPersonalAccessTokenManagerMockRecorder) CountActiveByOwner(ctx, realmName, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByOwner", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).CountActiveByOwner), ctx, realmName, sub)
}

// Create mocks base method.
func (m *MockPersonalAccessTokenManager) Create(ctx context.Context, token dao.PersonalAccessToken) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPersonalAccessTokenManagerMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).Create), ctx, token)
}

// GetByIDAndSub mocks base method.
func (m *MockPersonalAccessTokenManager) GetByIDAndSub(ctx context.Context, realmName string, id int64, sub string) (dao.PersonalAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndSub", ctx, realmName, id, sub)
	ret0, _ := ret[0].(dao.PersonalAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndSub indicates an expected call of GetByIDAndSub.
func (mr *MockPersonalAccessTokenManagerMockRecorder) GetByIDAndSub(ctx, realmName, id, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndSub", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).GetByIDAndSub), ctx, realmName, id, sub)
}

// GetByTokenHash mocks base method.
func (m *MockPersonalAccessTokenManager) GetByTokenHash(ctx context.Context, tokenHash string) (dao.PersonalAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(dao.PersonalAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockPersonalAccessTokenManagerMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).GetByTokenHash), ctx, tokenHash)
}

// ListByOwner mocks base method.
func (m *MockPersonalAccessTokenManager) ListByOwner(ctx context.Context, realmName, sub, state string) ([]dao.PersonalAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOwner", ctx, realmName, sub, state)
	ret0, _ := ret[0].([]dao.PersonalAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOwner indicates an expected call of ListByOwner.
func (mr *MockPersonalAccessTokenManagerMockRecorder) ListByOwner(ctx, realmName, sub, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOwner", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).ListByOwner), ctx, realmName, sub, state)
}

// Renew mocks base method.
func (m *MockPersonalAccessTokenManager) Renew(ctx context.Context, realmName string, id int64, sub string, expiresAt time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx, realmName, id, sub, expiresAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Renew indicates an expected call of Renew.
func (mr *MockPersonalAccessTokenManagerMockRecorder) Renew(ctx, realmName, id, sub, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).Renew), ctx, realmName, id, sub, expiresAt)
}

// Revoke mocks base method.
func (m *MockPersonalAccessTokenManager) Revoke(ctx context.Context, realmName string, id int64, sub string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, realmName, id, sub)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockPersonalAccessTokenManagerMockRecorder) Revoke(ctx, realmName, id, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).Revoke), ctx, realmName, id, sub)
}

// UpdateByIDAndSub mocks base method.
func (m *MockPersonalAccessTokenManager) UpdateByIDAndSub(ctx context.Context, realmName string, id int64, sub, name, description, audience string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByIDAndSub", ctx, realmName, id, sub, name, description, audience)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByIDAndSub indicates an expected call of UpdateByIDAndSub.
func (mr *MockPersonalAccessTokenManagerMockRecorder) UpdateByIDAndSub(ctx, realmName, id, sub, name, description, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByIDAndSub", reflect.TypeOf((*MockPersonalAccessTokenManager)(nil).UpdateByIDAndSub), ctx, realmName, id, sub, name, description, audience)
}
