name: bkauth ci

on:
  push:
    branches: [ main, pre_*, ft_*, release/* ]
    paths: ['src/bkauth/**']
  pull_request:
    branches: [ main, pre_*, ft_*, release/* ]
    paths: ['src/bkauth/**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache-dependency-path: src/bkauth/go.sum

    - name: Build
      run: make build
      working-directory: src/bkauth

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.61.0
        working-directory: src/bkauth

    - name: Test
      run: make dep && make test
      working-directory: src/bkauth
